/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */


#include "bureau.h"



int main () {
  
bureau_vote b_v;

int id,x;
float y=0,tn,et;

bureau_vote b_v1={0000,"tunis","esprit",55,10,20};
bureau_vote b_v2={9999,"ghazela","fst",12,25,30};
bureau_vote b_v3;

/**/
	x=ajoute("bureau.txt",b_v1);

if (x==1)
	printf("\n ajout de bureau avec succes \n");
	else printf("\n echec ajout \n");

/**/
	x=ajoute("bureau.txt",b_v2);

if (x==1)
	printf("\n ajout de bureau avec succes \n");
	else printf("\n echec ajout \n");

/**/
 	b_v1=chercher("bureau.txt",0 );

if(b_v1.ID_bureau_vote==-1)
	printf("\n observateur de id = %d n'existe pas \n",id);
 	else printf("\n observateur de id = %d existe \n",id);

/**/
	x=modifier(0, b_v2,"bureau.txt");

if (x==1)
	printf("\n modif de bureau avec succes \n");
	else printf("\n echec modif \n");


/**/
	x=supprimer(9999,"bureau.txt");

if (x==1)
	printf("\n supp de bureau avec succes \n");
	else printf("\n echec supp \n");

/**/
	taux("observateur.txt",&tn,&et);
		printf("\n le taux de tunisien est: %.2f%% \n \n le taux de etranger est: %.2f %% \n",tn,et);
	
/**/		
	
	y=TVB("utilisateur.txt");
		printf("\n le taux de vote blanc est : %.2f %% \n",y);
	
/**/
	
		
  return 0;
}

